### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by C-o-m-o-n** [0xyshv/Avatarify#1]
I got this error when I tried to generate my avatar

" CUDA out of memory. Tried to allocate 25.27 GiB (GPU 0; 47.41 GiB total capacity; 38.16 GiB already allocated; 7.12 GiB free; 38.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

do I need some api key or something?

**Comment by 0xyshv** [comment]
Hi Collins

Can you please confirm me that are you trying to generate your avatar using
the deployed app or have you cloned the repository, in case you have cloned
it you will need to set up your Replicate api token in your .env.local as
we are using the LLM of replicate model for avatar generation. In case you
are trying to generate your avatar using the deployed site , there is a
high chance that my free limit for using the replicate has exceeded so to
further use the GPU memory I'll have to pay the monthly subscription,
moreover please let me know by which method you are trying to generate the
avatar so that I can help you further.

You can connect with me on socials as well for a smoother communication.
Telegram : https://t.me/yashasvichaudhary
Discord : 0xyshv
LinkedIn : https://www.linkedin.com/in/0xyshv/
Twitter : https://twitter.com/0xyshv

**Comment by 0xyshv** [comment]
Hi Collins,

Please note that our project utilizes Replicate's models to generate avatars, and running it locally requires setting up the Replicate limited access API key.

**Comment by C-o-m-o-n** [comment]
> Hi Collins,
> 
> Please note that our project utilizes Replicate's models to generate avatars, and running it locally requires setting up the Replicate limited access API key.

Ok thanks, let me try it, I had tested it from the browser the other time. I'm sure that is the issue

**Comment by 0xyshv** [comment]
Sure, give it a try. If you further encounter any issue, feel free to ask.
